# Generated by Django 5.1.3 on 2024-12-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0004_alter_restaurant_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
