# Generated by Django 5.1.2 on 2024-10-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_reservation_number_of_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='number_of_people',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 orang'), (2, '2 orang'), (3, '3 orang'), (4, '4 orang'), (5, '5 orang'), (6, '6 orang'), (7, '7 orang'), (8, '8 orang')]),
        ),
    ]
