# Generated by Django 5.1.2 on 2024-10-26 00:19

import reservation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_reservation_number_of_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='id',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_id',
            field=models.CharField(default=reservation.models.generate_reservation_id, editable=False, max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
